//--------------------------------------------------  地图模块  -----------------------------------------

// 不能过图回调
function canNotPassMap(){
}

// 过图回调
function canPassMap(){
    // 如果是巡逻挂机中，切换地图时，更新当前地图的巡逻数据
    if(GAME_VARS.isHangUp && !GAME_VARS.isPatrol && !need_find_map){
        hook_status = 0;
        hook_map_name = gameEnv.mapName;
        printMessage(":巡逻挂机切换地图:" + hook_map_name);
    }
}